# Base R Shiny image
FROM rocker/shiny-verse

# Install R dependencies
RUN install2.r --error --deps TRUE shinyBS shinythemes shinyjs shinydashboard shinydashboardPlus shinyWidgets remotes

RUN R -e 'remotes::install_github("leeds-cdrc/nutrientprofiler@v1.0.0")'

# Copy Shiny app code
COPY server.R /srv/shiny-server/server.R
COPY ui.R /srv/shiny-server/ui.R
COPY www /srv/shiny-server/www
COPY R /srv/shiny-server/R
COPY shiny-server.conf /etc/shiny-server/shiny-server.conf

# Run the app
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/', port=8000)"]

# Expose the application port
EXPOSE 8000
